### ISSUE TITLE
I don't know why.

### ISSUE THREAD

**Issue by jgc9527** [TalTech-IVAR-Lab/ubuntu-desktop-docker#1]
![Screenshot_20221221_130305_com.server.auditor.ssh.client.png](https://user-images.githubusercontent.com/94273329/208825832-d22acdca-8768-4d35-b07e-919b2bf53227.png)

**Comment by jgc9527** [comment]
My command is
`docker run -d \
  --name=ubuntu-desktop \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=Asia/Shanghai \
  -p 3390:3390 `# rdp` \
  -p 2222:2222 `# ssh` \
  --shm-size="1gb" \
  --security-opt seccomp=unconfined \
  --restart unless-stopped \
  taltechivarlab/ubuntu-desktop:20.04`

**Comment by jgc9527** [comment]
@JGroxz @VladimirKutsTalTech

**Comment by tw-bert** [comment]
And you've read and followed the instructions?

From the readme:

---

#Once the container has started, you must ssh into it (default password is abc):

ssh abc@localhost -p 2222
...and change abc user's default password following the displayed instructions.

After that, you can use login abc and the newly set password to log in to the container using any remote desktop client.

**Comment by JGroxz** [comment]
> From the readme:
> 
> #Once the container has started, you must ssh into it (default password is abc):
> 
> ssh abc@localhost -p 2222 ...and change abc user's default password following the displayed instructions.
> 
> After that, you can use login abc and the newly set password to log in to the container using any remote desktop client.

This is correct.

@jgc9527 please use the default `abc` password when prompted for `Current password:` in SSH, after that you can set the new password. Let me know once it works.

**Comment by jgc9527** [comment]
Oh ~ he can connect it.I also want to ask what is the password of root user.

**Comment by jgc9527** [comment]
@JGroxz

**Comment by JGroxz** [comment]
> Oh ~ he can connect it.I also want to ask what is the password of root user.

The `root` account in this container is password less, as it is based on [linuxserver/rdesktop](https://github.com/linuxserver/docker-rdesktop). However, `abc` user has `sudo` access.

If you really want to access the container as `root`, you could enter the root shell by running `docker exec -it ubuntu-desktop /bin/bash` from the host machine, but I don't see a use case where it would be necessary.

EDIT: Quote.

**Comment by jgc9527** [comment]
Thank you very much.I think that's all my questions this time.😃😃😃

**Comment by JGroxz** [comment]
Good luck using it! Let us know if you face any other issues or have suggestions in the future.
